== La Carta de Elizabeth Webb

[.salutation]
Honorable amigo,^
footnote:[El destinatario de esta carta era Anthony William Boehm,
capellán del Príncipe Jorge de Dinamarca.
Parece que Elizabeth Webb conoció a Boehm durante una visita ministerial a Londres,
hacia el año 1712.]

Aunque casi soy una extraña para ti,
el amable respeto que me mostraste mientras estaba
en Londres me ha puesto bajo un gran deber,
en el que encuentro que mi mente es llevada a escribirte
en los movimientos del amor divino.
Lo que tengo que escribir ha estado en mi mente durante varias semanas,
en ese amor puro e inocente en el que la verdadera comunión de los santos es experimentada.
No he aprendido un método por el que pueda trasmitir mi experiencia religiosa,
ya sea por palabra o por escrito,
sino clara y sencillamente según el Espíritu de Verdad dirija.
Siendo además la vasija más débil, tengo una mayor necesidad de pedirte disculpas.
No escribiré a partir de conceptos y especulaciones (pues veo que
tales cosas no son seguras y sé que muchas veces tampoco son válidas),
sino una pequeña parte de lo que he atravesado y de lo que mi alma
ha gustado de la buena Palabra de vida que está cerca.

En verdad,
mi único deseo es que tengamos comunión en Dios el
Padre de nuestros espíritus y en Su Hijo,
Jesucristo nuestro Señor,
a quien mi alma ha experimentado tanto en misericordia como en juicio,
para humillación (en un buen grado) de la naturaleza caída y corrupta,
y para purificación de mi corazón de tal manera,
que no lo veo a Él (lo cual digo para Su alabanza) a través de formas, sectas,
grupos en particular o cualquiera de esas cosas.
No, mi estimado amigo, nunca busqué al Señor en esas formas,
ni para ninguno de esos fines.
Por el contrario, en mis años de juventud lo busqué para salvación,
y aún lo busco para la perfecta restauración de mi
alma en Él. No tengo nada de qué jactarme,
a menos que sean debilidades y flaquezas.
En realidad, me regocijo en la cruz de Cristo,
por la que soy crucificada al mundo en un buen grado y el mundo a mí,
a fin de que pueda decir: "`Muero cada día.`"

Con respecto a la inclinación a la educación, profesión religiosa y conversación,
estas cosas no han empañado mis ojos.
Puedo ver,
reconocer y amar la imagen de mi Señor y Salvador en cualquier tipo de profesión,
si el alma ha sido educada en la universidad celestial o escuela de Cristo.
Sin embargo, no podemos ver a Dios en toda forma de vida y conducta,
ni tener comunión con ello, porque el camino del impío es como si no hubiera Dios;
"`Dios no está en todos sus pensamientos.`"
El Señor despreciará en la otra vida,
la imagen de los que desprecien la imagen del Jesús manso y humilde,
y no sigan ninguno de Sus preceptos ni Su ejemplo de negación,
mientras estén aquí. Porque efectivamente,
ellos recibirán la imagen según la semilla o espíritu al que servían,
cuando sus cuerpos mueran.
Cada semilla tendrá su propio cuerpo en la resurrección del justo y del injusto,
y cada una recibirá su propia sentencia.

Ahora, mi estimado amigo,
te haré un breve relato de los tratos del Señor conmigo en mis años de juventud;
cómo llevó Él mi alma a través del fuego y del agua.
Para qué fin ha venido esto ahora a mi mente, no lo sé,
excepto que sea para nuestra comunión espiritual,
pero cuando mi alma está más humillada y más cerca del Señor en la sencillez de la verdad,
entonces mi corazón se abre y mi mente se llena del
amor divino con respecto a este asunto.
Deseo que lo examines internamente cuando estés apartado
y que no lo juzgues antes de que lo hayas terminado,
y luego júzgalo tan libremente como te plazca.

Fui bautizada y educada en la forma de la Iglesia de Inglaterra,
y fui instruida por uno de sus ministros,
un hombre que mostró gran amabilidad y ternura hacia mí,
y a quien amé y honré en gran medida.
En aquellos días yo veía a los ministros como ángeles
que traían buenas noticias a los hijos de los hombres.
Cuando tenía alrededor de catorce años fui a vivir a la casa de un caballero,
quien tenía un capellán. Estando ahí,
observaba la conducta de dicho capellán y veía que era vana,
y pensaba en mis adentros que no debía ser así y por eso mi mente estaba confundida.
Por aquellos días yo había empezado a pensar en mi final y en la eternidad,
y descubrí que no sentía ninguna seguridad de salvación o de un estado de felicidad,
si al Señor le placía enviar al mensajero de la muerte para llevarme.
Entonces el temor del Señor se apoderó de mi mente y empecé a escudriñar las Escrituras,
y encontré que ellas testificaban: "`Los impíos volverán al Seol,
junto con todas las naciones que se olvidan de Dios.`"
Y vi que tanto los sacerdotes como las personas en general "`se olvidan de Dios,`"
tan pronto como se levantaban de sus rodillas o salían de su devoción. Por tanto,
yo le tenía mucho miedo al infierno y no tenía seguridad
de un lugar en el reino de los cielos.

Entonces empecé a considerar las grandes promesas que me
fueron dadas en mi bautismo (como lo llamaban ellos),
mediante el cual, dijeron, era hecha miembro de Cristo e hija de Dios.
En esa ceremonia se dijo que yo debía renunciar al diablo y a todas sus obras,
a la pompa y vanidades de este mundo malvado, y a todo deseo pecaminoso de la carne,
y que debía guardar la voluntad y mandamientos santos de Dios.
Pensaba que esta era verdaderamente la manera de
obtener un lugar en el reino de los cielos,
pero me di cuenta de que no tenía el poder de hacer lo que debía hacer,
ni de abandonar lo que debía abandonar, pues era muy orgullosa, vana y superficial.
Pero a medida que era ejercitada internamente de esta manera,
y externamente continuaba escudriñando las Escrituras,
mi entendimiento se fue abriendo más y más. Leí y noté que los ministros
que Cristo calificaba y enviaba a predicar debían hacerlo gratuitamente,
porque Él había dicho: "`gratuitamente habéis recibido, gratuitamente dad.`"^
footnote:[Mateo 10:8 (Reina Valera 1602P)]
También encontré que aquellos que habían corrido cuando el Señor no los había enviado,
no eran "`de provecho alguno para este pueblo,`"^
footnote:[Jeremías 23, NBLH]
pero que el Señor había prometido pastores que vendarían
la herida y fortalecerían a la enferma.
(Ezequiel 34)

Muchas de esas cosas se abrieron en mi mente y yo solía reflexionar
en ellas en mi corazón. Estas y otras porciones similares de las
Escrituras llegaron a ser de mucho consuelo para mí,
porque yo estaba harta de mis pecados y mi corazón era quebrantado
muchas veces delante del Señor. Yo pensaba:
"`¡Oh, si yo hubiera vivido en los días de Cristo,
con seguridad habría sido una de los que lo siguieron!,`"
y me afligía porque los judíos lo habían crucificado.
Así amaba a Cristo en Su aparición externa y pude haber dicho con Pedro:
"`Lejos esté de Ti Señor sufrir!`"
Sin embargo,
yo no sabía entonces que Él estaba muy cerca de mí por medio de Su Espíritu Santo.

Entonces llegué a estar convencida de que los pastores asalariados,
'`los que enseñan por precio y adivinan por dinero`',
no son los verdaderos ministros de Cristo.
De hecho,
esto me fue manifestado por el testimonio de los profetas y por Cristo mismo cuando dijo:
"`Por sus frutos los conoceréis.`" Pues yo había continuado oyéndolos
hasta que un temor me siguió a la casa de adoración de ellos,
y entonces pensé que sería justo para el Señor hacer de mí un ejemplo,
por mi desatención al Espíritu de verdad.
Así, finalmente dejé de ir a oírlos y empecé a caminar sola.

Cuando tenía aproximadamente quince años,
le plació a Dios enviar al Espíritu de gracia y súplica a mi corazón,
por medio del cual oraba fervientemente al Señor. En verdad
se levantó una respiración divina en mi alma,
pero no podía encontrar vida en ninguna de las formas de oración,
excepto en la que Cristo les había enseñado a Sus discípulos
(por la que yo siempre había tenido un reverente aprecio).
Sin embargo, cuando estaba en oración,
hallaba que el Espíritu hacía intercesión en mí y por mí,
de acuerdo con la necesidad presente en mi alma.
Recuerdo las expresiones que solían pasar por mi mente: "`¡Señor,
presérvame en Tu temor y en Tu verdad! ¡Señor,
muéstrame Tu camino y dame a conocer Tu pensamiento y Tu voluntad!`"
Yo pensaba que estaba lista para obedecerlo entonces,
y mi gran deseo era conocer al pueblo de Dios, por lo que mi alma clamaba: "`¡Señor,
¿dónde apacientas Tu rebaño? ¿Por qué había de estar
yo como errante tras los rebaños de Tus compañeros?!`"

¡Oh,
las cuerdas de divino amor con las que me atrajiste! ¡Atrajiste mi alma con anhelos
y respiraciones en pos del conocimiento del único Dios verdadero y de Jesucristo!
En ese entonces no experimentaba ninguna condenación por los pecados de ignorancia,
pues Dios los había pasado por alto,
pero me llamaba al arrepentimiento y a abandonar mi orgullo y vana compañía,
lo cual fue una gran cruz para la voluntad de la carne.
Sin embargo, tomé esa cruz por varios meses, y mientras lo hice,
mi alma tuvo gran paz y consuelo divino,
de modo que muchas veces el deleite del amor divino era más para
mí que la comida natural o que cualquier otra cosa externa.
Recuerdo que cuando la familia me preguntaba por qué no había ido a comer,
yo pensaba en mis adentros: "`Tengo una comida que comer, de la que no saben nada.`"
Y en mis tiempos de retiro se me mostraban sufrimientos por los que debía pasar,
y la visión de varias cosas con las que me he topado desde entonces;
pero en aquellos tiempos yo caminaba sola.

Yo fui convencida muy temprano de que los cuáqueros sostenían los principios de la Verdad,
y que su ministerio era el verdadero ministerio,
pero en ese entonces vivía lejos de cualquiera de ellos.
Sin embargo, cuando tenía unos doce años estuve en una o dos de sus reuniones,
y una vez sucedió,
que la doctrina de un hombre que estaba predicando
resultó ser (como lo llama el hombre sabio),
'`como pan echado sobre las aguas,
el cual es hallado después de muchos días.`' En efecto,
su voz parecía sonar en mi mente cuando estaba sola
y algunas de sus palabras llegaban frescas a mi memoria,
lo que era muy conveniente para el ejercicio de mi mente.
En ese tiempo también encontré un librito de ellos,
y al descubrir que la doctrina que contenía estaba
de acuerdo con la doctrina de los apóstoles,
fui confirmada en mi juicio de que ellos profesaban la Verdad.
Pero no me uní a ellos entonces,
porque por ese tiempo mi carne y sangre empezaban a sentirse
muy incómodas bajo el yugo del retiro interior,
y gemían buscando libertad.

Cuando tenía unos dieciséis años,
descubrí que la sutileza del enemigo yacía cerca y que él no carecía de instrumentos.
Fui persuadida por el razonamiento con la carne y sangre,
que podía buscar un poco más de placer puesto que aún era joven, y que luego,
cuando fuera mayor, podía servir a Dios.
Así que dejé mi ejercicio de vigilancia y oración, dejé que mi retiro diario se apagara,
y que saliera mi amor hacia muchos objetos visibles.
El orgullo y la vanidad crecieron en mi de nuevo, y el Espíritu divino, dulce,
manso y amoroso se retiró, y aunque a veces lo buscaba,
no podía encontrarlo otra vez cuando me placía. Sí,
yo habría estado muy complacida con el dulce consuelo de Su amor entonces,
pero no quería llevar Su cruz cada día. Y así,
habiendo sido convencida de los principios de los cuáqueros,
y creyendo que ellos disfrutaban la dulzura del amor divino en sus reuniones,
a veces caminaba grandes distancias para buscar divino refrescamiento con ellos.
Pero esto no logró dicho propósito,
porque yo era como un palo seco que no tenía savia ni virtud,
para el que la lluvia y el sol, el verano y el invierno eran iguales.
Así estuve por cerca de tres años. ¡Oh,
el recuerdo de ese tiempo perdido! ¡La tribulación
que vino sobre mí por mi desobediencia no debe olvidarse!

Sin embargo, cuando estaba cerca de los diecinueve años,
le plació al Todopoderoso enviar de nuevo Su Espíritu vivificante a mi corazón,
y Su luz brilló en mi mente.
Todas mis transgresiones fueron puestas en orden delante de mí,
y fui profundamente consciente de mi gran pérdida.
Y luego... ¡Oh, luego,
las copas de ira de un Padre enojado fueron derramadas sobre
la naturaleza de transgresión en mí! Entonces clamé:
"`¡Ay de mí! ¡Ay de mí! ¡Estoy perdida;
he matado al Niño de gracia! ¡He crucificado de nuevo para mí al Señor de vida y gloria!`"
Porque,
aunque en todo ese tiempo había sido preservada en honestidad moral en todos los aspectos,
al punto de que nunca me atreví a decir una mentira,
ni a pronunciar una palabra corrompida,
y podía estar confiada en cualquier lugar y en cualquier cosa, aún así,
y a pesar de mi justicia externa,
Aquel cuyos ojos penetran todos los corazones me halló tan culpable,
que pensé que no había misericordia para mí. En efecto,
me di cuenta de que el testimonio de nuestro bendito Señor Jesús es verdadero, a saber:
Salvo que tu justicia exceda la justicia de los escribas y fariseos,
no hay entrada al reino de los cielos ni al favor de Dios.

Entonces, después de muchos días y noches de tristeza y gran angustia,
vino a mi mente (sin haber hablado con ninguna alma) rendirme en las manos de Dios.
Dije: "`¡Oh Señor, si perezco, que sea a la puerta de Tu misericordia!
Porque si me arrojas al infierno, no puedo evitarlo, por tanto, entrego en Tu santa mano,
mi alma, mi vida, todo.
Haz lo que te plazca conmigo, pues Tus juicios son justos,
y yo he ignorado Tu dulce amor y he matado al Niño de gracia.`"
Y mientras me hundía en la muerte y reconocía y me sometía a los juicios de Dios,
mi corazón (que había sido duro) fue quebrantado,
y le plació a mi Padre misericordioso hacer que Su divino y dulce amor brotara de nuevo,
como un manantial de agua viva, en mi alma dura, seca y estéril.
Luego,
el fuego de la ira de Dios fue poderosamente aplacado y
mi alma sintió las compasivas entrañas del tierno Salvador,
y una esperanza viva se levantó en mi mente.

Sin embargo, después vinieron mayores aflicciones, de manera que aprendí por experiencia:
"`Estrecha es la puerta y angosto el camino que lleva a la vida.`"
Tengo motivos para creer que nadie,
sino los que están dispuestos a ser desnudados de
todo lo que le pertenece al yo o al viejo hombre,
y se hacen como niños, pueden entrar correcta o verdaderamente por la puerta estrecha.
De hecho, encuentro por experiencia, que ni el ojo del buitre, ni la bestia venenosa,
ni el noble cachorro de león, pueden mirar o caminar por esta senda estrecha y santa.
¡Oh, el anhelo que hay en mi alma de que todos la consideren así!

Prosiguiendo: Yo creía que todo estaba bien y decía en mi corazón:
"`Ya pasó lo peor y he vuelto al favor de Dios.`"
Así que mi gozo se incrementó, aunque yo internamente permanecía en silencio.
Pero en pocos días mi alma fue conducida al desierto, donde no había camino, ni guía,
ni luz que yo pudiera ver, sino tal oscuridad que la podía sentir.
En realidad,
los horrores de ella eran tales que cuando era de noche yo deseaba la mañana,
y cuando era la mañana deseaba la noche.
¡El Señor estaba cerca,
pero yo no lo sabía! Él había llevado mi alma al desierto y allí
litigó conmigo por medio de Su ardiente ley y justos juicios.
El Día del Señor había llegado sobre mí y ardía como un horno en mi seno,
hasta que todo el orgullo y la vanidad fueron quemados.
Mis deleites anteriores se fueron,
mis viejos cielos desaparecieron dentro de mí (como con fuego),
y mi mente fue ejercitada en angustia y tristeza tanto como pude soportar,
día y noche por varios meses, sin una gota de consuelo divino.
Mi corazón estaba como un carbón encendido, o como un hierro candente,
y no sentía quebrantamiento de corazón o ternura de espíritu.
Y aunque yo clamaba a Dios continuamente en la profunda angustia de mi alma,
ni una lágrima salía de mis ojos.
¡Oh, los días de tristeza y las noches de angustia por los que pasé,
no hay lengua que lo pueda expresar,
ni corazón que lo pueda concebir si no ha pasado por lo mismo!
Me habría gustado ser otra criatura, para no experimentar tanta angustia y tristeza,
porque pensaba que las otras criaturas estaban contentas en sus lugares apropiados.

Mis dificultades fueron agravadas por la fuerte opresión y tentación de Satanás,
que no estaba dispuesto a perder a ninguno de sus súbditos.
Él levantó todas sus fuerzas e hizo uso de todas las armas que tenía en la casa.
En realidad, me di cuenta de que era como un hombre fuerte armado,
porque no me permitió entrar en un estado de rendición,
sino que me llevó a indagar los misterios que pertenecen
a la salvación con el ojo de la razón carnal.
Y como no podía comprender con ese ojo,
me hizo cuestionar la verdad de todas las cosas que
quedaron registradas en las Sagradas Escrituras,
y hasta me había persuadido a creer la opinión de los judíos con respecto a Cristo.
Muchos otros cebos y falsos lugares de reposo fueron puestos delante de mí,
pero mi alma estaba hambrienta del verdadero pan, del pan de vida,
del que vino de Dios desde el cielo (del que Cristo testifica en Juan 6),
el cual yo había sentido cerca y mi alma había gustado.
Y aunque el diablo me provocaba con sus tentaciones,
mi alma no podía alimentarse de ellas, sino que clamaba continuamente:
"`¡Tu presencia Señor, o si no muero! ¡Déjame sentir Tu brazo salvador,
o perezco! ¡Oh Señor, dame fe!`"
De esta manera era ejercitada mi alma con fervientes súplicas a Dios día y noche,
y aún así, yo cumplía con mis responsabilidades externas y sólo gemía delante de Dios.

Desde entonces,
a menudo he reflexionado en cómo la sutil serpiente
encuentra cebos adecuados para las almas,
especialmente para las que se contentan con un alimento
menor que el deleite mismo de Dios.
Tras haber conocido los terrores de Dios y las sutiles artimañas de Satanás,
a veces era llevada a persuadir a la gente al arrepentimiento
y advertirla a que huya de la ira venidera.

Toda la fe que había experimentado antes (mientras aún estaba en desobediencia),
resultó ser como una casa sobre un cimiento de arena.
Todo el consuelo que anteriormente experimentaba al leer las Escrituras fue quitado,
y por un tiempo no me atreví a leer,
porque hacerlo le sumaba a mi condenación. Dependía sólo de Dios,
quien a veces me hacía sentir una pequeña esperanza,
como un destello de luz debajo de mis angustias.
Este era como un puntal para mi alma, y de no haber sido así,
de seguro habría caído en la desesperación.

Mi mayor deseo era ser llevada a través de mis problemas por el camino correcto,
y no sacudirlos ni superarlos en mi propio tiempo.
Por tanto, nunca tuve la libertad de darle a conocer mi condición a nadie,
porque pensaba en mis adentros: "`Si el Señor no me ayuda,
vana es la ayudad del hombre.`"
Desde entonces he visto que estuvo bien no hacerlo (por varias razones),
y que habría incurrido en una pérdida si lo hubiera hecho.
Pues ahora sé que la voluntad de Dios era humillarme,
y exponer y derribar toda ayuda que pudiera haber sido imputada al hombre o al yo,
para que yo experimentara la verdadera obra del Señor
levantarse del fundamento de Su propio poder,
donde no hay nada edificado por el hombre y toda la gloria
es dada únicamente a Él. Porque nosotros tendemos a decir,
en efecto: "`Yo soy de Pablo, yo soy de Apolos, yo soy de Cefas,
y yo de Cristo,`" como si Cristo estuviera dividido;
pero el Señor no le dará Su gloria a otro, ni Su alabanza a imágenes talladas.
Porque como tú, mi amigo, has observado bien,
el principal fin para el cual debemos trabajar,
es hacer que la gente sea consciente de su corrupción,
dirigirlos a la Palabra que está cerca y ser buenos ejemplos para ellos.

Así, en el debido y señalado tiempo del Señor,
cuando Él vio que el sufrimiento que me consumía era suficiente,
le plació hacer que Su divino amor fluyera en mi corazón en forma extraordinaria,
y que el Espíritu Santo de luz y vida divinas venciera mi alma.
Luego, me fue dado un sentido divino y un entendimiento,
por medio de los cuales conocer el poder y el amor de Dios al enviar desde Su seno,
a Su unigénito Hijo al mundo, tomar para Sí un cuerpo de carne,
y atravesar todo el proceso de sufrimiento para salvación de la humanidad.
Vi cómo se abrió paso,
abrió las puertas de la muerte y reparó la brecha que el
primer Adán había abierto entre Dios y el hombre,
y restauró la senda para que las almas puedan venir a Dios.
Se le dio a entender a mi alma sencilla,
cómo envió el Todopoderoso al Espíritu de Su Hijo a mi corazón,
a fin de que me guiara a través del proceso de Sus sufrimientos,
para que así como Él murió por el pecado,
yo muriera al pecado al llevar diariamente la cruz y vivir en negación del yo,
humildad y obediencia a Dios, mi Padre celestial,
en todas las cosas que Él requiriera de mí.

Luego mi alma experimentó el bautismo del Espíritu
Santo (que es comparado tanto con agua como con fuego),
y vi que el ministerio de juicio y condenación tenía una
gloria en él que le abría paso al ministerio de vida.
El hacha de la Palabra viva de Dios fue puesta a la raíz del árbol malo,
y mi alma oyó la voz de Aquel que predicaba el arrepentimiento,
y clamaba que todo monte y collado se bajaran y que todo valle se alzara (es decir,
los montes de mi temperamento natural),
para que una calzada llana fuera formada y el alma rescatada pudiera caminar por ella.
El Señor me mostró cómo Juan el Bautista llegó a ser considerado
el más grande profeta nacido de una mujer,
pues fue el precursor de Jesucristo, y que, en realidad,
el más pequeño en el reino de los cielos es mayor que aquel
que está únicamente bajo el ministerio de Juan.
Porque el ministerio de Juan tenía que menguar y el de Jesús crecer,
cuyo bautismo es con el Espíritu Santo y fuego,
y con el que Él quiere purificar Su era por completo.

Entonces tomé consciencia de que en verdad es obra de Dios,
creer correcta y verdaderamente en Aquel que Él ha enviado,
que esta fe purificadora y salvadora es don de Dios,
y que el brote mismo y principio vital de esta es el amor divino.
Entonces lloré por Aquel a quien yo había traspasado
con la incredulidad y dureza de mi corazón,
y comí mi pan con llanto y mezclé mi bebida con lágrimas.
Yo tenía entre diecinueve y veinte años de edad cuando
estos grandes conflictos estaban sobre mí,
mediante los cuales fui llevada a gran humillación.

Por tanto, entré en un pacto solemne con el Dios Todopoderoso,
prometiéndole que respondería a Sus requerimientos,
aun sí estos significaban la entrega de mi vida natural.
Pero cuando se me mostró que debía tomar la cruz en las cosas pequeñas,
fui rápida para escuchar de nuevo al razonador y fui desobediente en el día de las pequeñeces.
Porque, aunque había pasado por mucha prueba interna,
todavía tenía miedo de disgustar a mis superiores,
siendo por ese tiempo la criada de personas de renombre en el mundo.
Se me mostró que yo no debía darle títulos aduladores al hombre,
y tenía mucho miedo de que el Señor me quitara otra vez Su buen Espíritu
si yo no obedecía lo que Él requería de mí. Así que estaba en gran apuro;
tenía temor de desagradar a Dios y temía desagradar al hombre.
Al final, fui acusada por el Espíritu de honrar más al hombre que a Dios.
Pues cuando me dirigía a Dios usaba un lenguaje sencillo,
pero cuando hablaba con un hombre o con una mujer, le hablaba de otra manera,
de lo contrario se habría ofendido.
Vi que el orgullo del hombre no estaba dispuesto a recibir ese lenguaje de un inferior,
el mismo que él le daría libremente al Todopoderoso.
Por tanto,
esto llegó a convertirse en una gran cruz para mí y en un
obstáculo en el camino de progreso de mi alma,
hasta que me rendí a la exigencia del Señor en esta pequeñez.

Te digo estas cosas, estimado amigo, con gran sencillez,
para que veas cómo saca el Señor de las costumbres vanas que hay en el mundo,
no sólo en estas cosas que he mencionado, sino también en muchas otras.
Y que igualmente,
Él guía a esa manera humilde y de negación al yo que Cristo enseñó y practicó,
cuando era visible entre los hombres.
De hecho, Cristo es el verdadero modelo de los cristianos y Su Espíritu el Líder de ellos.

Hablo estas cosas en verdad y con sinceridad, porque no deseo que me malentiendas.
Soy un alma simple, completamente dedicada al Señor,
y no abogo por ninguna forma externa por causa de la forma,
ni tampoco abogo por una secta o grupo en particular como pueblo.
Pues tristemente, aún nosotros nos hemos convertido en un pueblo mezclado,
al igual que los hijos de Israel cuando estaban en el desierto.
Pero esto sí lo puedo decir para alabanza y gloria de Dios:
El principio que nosotros profesamos es la Verdad misma, a saber,
Cristo la esperanza de gloria en el hombre y en la mujer.
Y Cristo, como sabes, es el Camino, la Verdad y la Vida,
y nadie llega a Dios sino por Él. Por tanto,
hay un remanente que es fiel al Señor su Líder espiritual
(como Josué y Caleb en la antigüedad),
que lo sigue fielmente y se mantiene firme en sus
testimonios contra todas las formalidades muertas,
que no son más que imágenes sin valor cuando carecen del principio vivo.
Así como el Espíritu de Jesús saca de todas las vanas
costumbres y tradiciones que están en el mundo,
y conduce a la vida sencilla, humilde, mansa, de negación al yo,
y al camino en el que Cristo caminó mientras era visible entre los hombres,
yo deseo que todos sigan la guía de Su Espíritu,
para que en verdad lo confiesen delante de los hombres.

Sin embargo,
si al Todopoderoso le placiera aceptar almas sin guiarlas
a través de ardientes pruebas tal como hizo conmigo,
o sin exigirles cosas como las que me exigió a mí,
lejos esté de mí juzgar que estas no hayan experimentado al Señor o la morada de Su amor,
si los frutos del Espíritu de Jesús están claramente en ellas.
Porque cada árbol es conocido por sus frutos y para
nuestro propio Señor estamos de pie o caemos.
Pero, querido amigo, como bien has observado, la purificación es una obra gradual;
lo digo por experiencia.
Porque cuando el antiguo adversario no pudo arrastrarme
más hacia vanas conversaciones y bromas tontas,
entonces me turbaba con vanos pensamientos,
algunos de los cuales estaban en concordancia con
mi disposición natural y otros eran muy contrarios.
¡Oh,
entonces clamaba fuertemente ante el Señor en busca de poder sobre los vanos pensamientos,
porque eran una gran angustia para mí! Y me mantenía con gran temor
de caer un día u otro por causa de la mano del enemigo.
Pero el Señor consolaba mi alma con Sus propias palabras (las dejadas en el relato):
"`No temáis, manada pequeña, porque a vuestro Padre le ha placido daros el reino.`"
Con estas palabras el Señor me dio evidencia de que mi alma era una de esa manada pequeña.

En otra ocasión, estando muy humillada en mi mente,
brotaron estas palabras con vida y virtud: "`Bien que fuisteis echados entre los tiestos,
seréis como alas de paloma cubiertas de plata,
y sus plumas con amarillez de oro`" (Salmo 68:13) ¡Oh,
cuán maravillosamente consolador fue para mí,
cuando el Espíritu Santo trajo esta promesa a mi recuerdo
y me dio evidencia de que esta era mi porción! Por tanto,
reflexioné con respecto a "`las alas de paloma`"
y pensé que ellas debían ser las alas de inocencia,
por las que mi alma podía ascender a Dios en oración,
meditación y divina contemplación. Yo me deleitaba orando
en secreto y ayunando en secreto del vagabundeo de mi mente,
tanto como podía,
y mi Padre celestial (que ve y oye en lo secreto) me recompensaba en público.
Pues en ese entonces, cuando iba a las reuniones, no me sentaba en tinieblas,
sequedad y esterilidad como solía suceder en el tiempo de mi desobediencia, en su lugar,
cosechaba el beneficio de la venida de Cristo, quien dijo:
"`El ladrón no viene sino para hurtar y matar y destruir;
yo he venido para que tengan vida, y para que la tengan en abundancia.`"
El ladrón, en el tiempo de mi desobediencia, le había robado mi alma a Jesús, quien dijo:
"`El que ama a padre o madre... (o su propia vida más que a Mí),
no es digno de mí.`" Así había sucedido conmigo y por varios
años no había podido cosechar el propósito de Su venida.
Pero Él regresó en misericordia y le dio a mi alma
inclinada el deleite de Su divina presencia,
y le plació hacer que Su amor (que es la verdadera vida
del alma) abundara en mi corazón en las reuniones,
tanto que mi copa rebosaba.
Yo era constreñida bajo un sentido del deber,
a arrodillarme en la congregación y confesar la bondad de Dios,
y pedirle a Él que esta continuara.
Le pedía poder para caminar digna del gran favor,
beneficio y misericordia que había recibido de Su generosa mano.

Recuerdo que después de haber hecho pública confesión de la bondad de Dios,
mi alma se sentía como si hubiera estado en otro mundo.
Estaba tan iluminada y animada por el amor divino,
que sentía amor por toda la creación de Dios, y vi que todo estaba bien en su lugar.
Se me mostró que las cosas deben ser mantenidas en sus propios lugares:
Que el cerdo no debe entrar en el jardín,
ni los animales limpios deben ser llevados a la recámara,
que así como era en la creación externa, debe ser en la creación interna y nueva.
Todo comenzó a predicarme: La fragancia de las hierbas y las flores hermosas e inocentes,
tenían una voz que le hablaba a mi alma,
y las cosas parecían tener un gusto diferente al de antes.
Los juicios de Dios eran dulces a mi alma, y en algunas ocasiones,
Él me hacía llamar a otros para que vinieran a gustar y a ver cuán bueno es el Señor,
y en otras, me hacía exhortarlos a probar al Señor caminando delante de Él, obediente,
humilde e inocentemente.
Entonces verían que Él quiere derramar Sus bendiciones espirituales de manera tan plena,
que no habría suficiente lugar para contenerlas,
y que el desbordamiento regresaría Al que es la Fuente con acción de gracias.
A veces era llevada a advertirles a las personas que no debían provocar al Señor desobedeciendo,
pues aunque Él soporta y sufre mucho tiempo (como
lo hizo con los israelitas rebeldes en el desierto),
todos conocerán que Él es un Dios de justicia y juicio, y tendrán que confesarlo.

Así, estimado amigo,
te he dado un claro pero verdadero relato de mi calificación
y llamado al servicio del ministerio.
Sin embargo, pasaron varios años antes de que yo llegara a un estado de libertad,
y a un temperamento estable.
Porque algunas nubes querían levantarse e interponerse entre mi alma y el Sol naciente,
y a menudo era arrojada en el horno.
Pero descubrí, por experiencia,
que cada vez que mi alma era arrojada en el horno de aflicción,
se levantaba más limpia y brillante.
Y a pesar de que la nube se interponía entre el Sol naciente y yo,
cuando el Sol de justicia aparecía de nuevo,
Él traía sanidad bajo Sus alas y estaba más cerca que antes.
Expreso estas cosas en sencillez,
como me fueron representadas y hechas manifiestas en la mañana de mi día.

Llegué a amar el vivir con juicio, y solía orar con frecuencia diciendo: "`¡Señor,
escudríñame y pruébame,
porque Tú conoces mi corazón mejor de lo que yo lo conozco! ¡No
permitas que ningún engaño o injusticia se aloje en él,
y deja que Tus juicios pasen sobre todo lo que es contrario a Tu naturaleza pura y divina,
en mí!`" De esta manera mi alma solía respirar al Señor continuamente,
con hambre y sed de un más completo disfrute de Su presencia.
Y aunque Él es fuego consumidor de la naturaleza corrupta del viejo hombre,
mi alma amaba morar con Él. Descubrí que muchos tipos
de corrupciones trataban de brotar en mí de nuevo,
pero rendí mi mente al Señor con deseos de que Él me alimentara
con comida apropiada para mí. Y puedo decir por experiencia,
que el alma que nace de Dios respira por Él tan constantemente en oración,
como un recién nacido respira y exhala aire.
Sí, de esta misma manera el hijo de Dios aspira y respira el aliento de vida,
mediante el cual el hombre fue hecho un alma viviente para Dios.
Pero todos aquellos que todavía están en el viejo hombre o naturaleza caída,
no experimentan nada de este aliento puro y divino, pues es un misterio para ellos;
sin embargo, el bebé en Cristo sabe que es verdadero.
Aunque los hijos de la familia de nuestro Padre son de varias edades,
crecimientos o estaturas (en cuanto a fuerza y entendimiento),
he observado en mis viajes: Que los que viven para Dios,
continúan en un estado de respiración hacia Él mientras están aquí,
y continuamente tienen hambre y sed de un más completo deleite de Su divina presencia.
De este modo, aunque es cierto que cada día que pasa nos acerca a la tumba,
también es cierto que cada día que pasa,
puede llevar al alma a una mayor unión y comunión con Dios.
Para mí,
cuando encuentro un alma respirando dulcemente para
Dios y hambrienta y sedienta de Su justicia,
es señal segura de vida y salud divinas en ella.
En realidad,
por la manera de vida de alguien se puede ver claramente y con
facilidad saber qué tipo de espíritu gobierna dentro de esa persona.
¡Es cierto, muchos no creerán estas cosas, ni probarán si lo son o no, en su lugar,
están satisfechos con la cáscara de la religión! Pero,
¿qué harán cuando los rudimentos y pobres elementos de este mundo
caigan y todas nuestras obras deban pasar a través del fuego?
¡Mi alma se lamenta por ellos!
Pero nosotros debemos avanzar y dejarlos si no quieren
levantarse y salir de su falso reposo.

Estimado amigo, como bien observas,
es de gran ayuda para el alma conocer su propia corrupción y entender de dónde ha caído,
para que pueda saber cómo regresar.
Estas cosas son muy ciertas, y el conocimiento de ellas ha sido de gran consuelo para mí,
como también tener las experiencias de los siervos del Señor
junto con los testimonios que dejaron registrados,
que son como marcas en el camino para el viajero espiritual.
En verdad tenemos un gran privilegio en y por estos, y por encima de todos,
en Cristo nuestro Modelo santo y Líder celestial que dijo: "`Mi juicio es justo,
porque no busco mi propia voluntad,
sino la voluntad de mi Padre que me envió.`" Mi alma valora
el conocimiento de Sus pisadas y la guía de Su Espíritu,
el Espíritu de Verdad, el Consolador,
a quien el Padre ha enviado para guiarnos a toda verdad.
"`¡Oh!`" dice mi alma,
"`¡ojalá nosotros siguiéramos la guía de nuestro infalible Líder
en todas las cosas a las que Él nos guíe!`" Tengo buena razón para
creer que Él nos quiere llevar a través de tribulaciones,
tanto para el honor de Dios como para nuestro consuelo,
porque el Señor ha llevado mi alma a través de muchas pruebas, una tras otra,
según Él ha visto conveniente, a algunas de las cuales haré alusión en lo que sigue.

Después de que mi tribulación interna había disminuido, empezaron las pruebas externas,
algunas de las cuales no fueron poca cosa,
y trataron con toda su fuerza y astucia de impedir que la obra del Señor prosperara
en mí. Porque así como Saúl cazaba a David e intentaba quitarle su vida natural,
así cazaban estas pruebas mi alma para quitarle la vida que tenía en Dios; sin embargo,
todas obraron para mi bien.
He visto a menudo, y por tanto puedo decir,
que el Señor sabe qué es mejor para Sus hijos mucho mejor de lo que nosotros lo sabemos.
Y así, mis enemigos, en lugar de alejar mi alma de Dios, la acercaron a Él. Sí,
estas pruebas me hicieron probar el espíritu que tenía el dominio en mi mente,
y encontré que era el Espíritu de Verdad,
el que la mente mundana y egocéntrica no puede recibir.
Pues descubrí que la naturaleza de ella era inofensiva y santa,
y que me guiaba a amar a mis enemigos, a tener compasión de ellos y a orar por ellos.
Este amor era mi preservación,
y conforme me entregaba en obediencia a la operación
y requerimiento de este Espíritu manso,
Él le ministraba paz a mi alma como el mundo no la puede dar.

Sin embargo, todavía había en mí una disposición de agradar a todos,
de la que me resultó muy difícil ser destetada para permanecer pura para Dios.
Hallé que cuando le temía al hombre, no tenía más que angustia y dolor,
y a menudo caminaba sola y derramaba mi lamento al Señor. Pero después de un largo tiempo,
cuando el Señor había tratado mi fidelidad hacia Él según lo consideró conveniente,
un día mientras estaba sentada en una reunión en silencio,
esperando en el Señor experimentar mi fuerza renovada en Él,
esta porción de las Escrituras me fue dada: "`Consolaos, consolaos, pueblo mío,
dice vuestro Dios.
Hablad al corazón de Jerusalén; decidle a voces que su tiempo es ya cumplido,
que su pecado es perdonado;
que doble ha recibido de la mano de Jehová por todos sus pecados.`"
Esta trajo gran consuelo a mi alma y la atesoré en
mi corazón. Observé que a partir de ese momento,
el Señor le dio a mi alma (según lo expresa el apóstol Pedro),
una entrada más generosa al reino de los cielos o Nueva Jerusalén,
cuyas murallas son salvación y sus puertas alabanza.
En realidad,
mi mente fue llevada a mayor quietud y los pensamientos
gravosos fueron expulsados en un buen grado.
Mis enemigos externos se cansaron de su obra y abandonaron su esperanza;
la alabanza de lo cual yo libremente (y en gran humildad)
ofrezco y adscribo a Dios Todopoderoso,
porque fue obra Suya preservarme de tantas tentaciones fuertes.

Así, después de haber sido favorecida con paz en casa en todos los sentidos,
fui persuadida por el Espíritu de amor a viajar al norte de Inglaterra.
En mi viaje, mi alma tuvo muchos combates con el espíritu maligno,
tanto cuando estaba dormida como cuando estaba despierta.
Mientras dormía me atormentaba tanto como podía,
pero me fue dado abundante valor para hacer guerra contra él,
lo cual consolaba mucho mi mente.
En consecuencia,
buscaba fervientemente al Señor para que me diera la misma
victoria sobre el diablo cuando estaba despierta,
es decir, de la misma manera que me la daba a conocer cuando estaba dormida.
El Espíritu que me conducía era para mí como la aguja de una brújula,
pues me señalaba adónde debía ir.
En aquellos días yo tenía ciertas manifestaciones de muchas cosas en sueños,
los cuales sucedieron conforme a sus significados.
De hecho, muchas veces fui prevenida de mis enemigos,
y como resultado estaba mejor equipada para protegerme de ellos.
Yo viajaba con gran temor y humildad,
y el Señor estaba conmigo para Su gloria y mi consuelo,
y me llevó a casa de nuevo en paz.

En el sexto mes del año 1697, mientras estaba sentada en la reunión en Gloucester,
Inglaterra (que era entonces el lugar donde vivía),
mi mente fue recogida en perfecta quietud por un tiempo.
Parecía como si mi espíritu hubiera sido llevado a América, y cuando regresó,
mi corazón estaba derretido por el amor de Dios,
el cual fluyó sobre el gran océano y me constriño a arrodillarme
y a orar por la semilla de Dios en América.
Esta preocupación nunca salió de mi mente, ni de día ni de noche,
hasta que me rendí para viajar ahí en el amor de Dios (el cual es un amor tan universal,
que alcanza tierra y mar).
Pero cuando vi la perspectiva desde el ojo de la razón humana,
me parecía algo muy extraño y difícil,
pues yo no sabía nada del país ni de nadie que viviera ahí. Razoné mucho con
respecto a mi propia incapacidad y cuando dejé entrar estos razonamientos,
no sentí nada sino muerte y oscuridad, y los problemas acudieron a mi mente.
Pero cuando le entregué todo al Señor y accedí en mi mente ir,
entonces el amor divino brotó en mi corazón y mi alma tuvo
libertad para adorar al Señor en la tierra de los vivos.

Así consideraba y probaba la perspectiva de ir a América en mi propio corazón,
hasta que finalmente estas palabras corrieron por mi mente con autoridad:
"`Los temerosos e incrédulos tendrán su porción con el hipócrita,
en el lago que arde con fuego y azufre; que es la segunda muerte.`"
Esto trajo pavor sobre mí,
y entonces le conté a mi esposo que sentía la necesidad de ir a América y le
pregunté si él estaría dispuesto a renunciar a mí. Él dijo que esperaba que Dios
no lo requiriera de mí. Entonces le dije que el Señor ya lo había hecho,
pero que yo no iría sin su libre consentimiento,
lo cual al principio pareció un poco difícil para
él. Poco después me enfermé de una fiebre violenta,
que me trajo tal debilidad que todos los que me veían pensaban que no me recuperaría.
Pero estando convencida de que mi día de trabajo no había terminado,
mi principal preocupación durante la enfermedad era mi viaje a América.
Algunos se inquietaban cuando yo hablaba acerca de esto abiertamente,
porque pensaban que yo con seguridad moriría,
y entonces algunos tenían motivos para hablar en mi contra con reproche.
Otros me insistían en que, aun cuando yo me recuperara,
mi barco estaría listo para zarpar mucho antes de que yo estuviera en condiciones de ir.
Pero yo pensaba que si ellos me cargaban y me acostaban en el barco, yo estaría bien,
porque el Señor había sido muy misericordioso con mi alma en el tiempo de mi enfermedad,
y me había dado la promesa de que Su presencia iría conmigo.
Entonces mi esposo realmente se dispuso a renunciar a mí, pues dijo,
que aunque yo estuviera lejos siete años,
eso sería mejor a que yo le fuera quitada para siempre.

Cuando finalmente todos los obstáculos fueron quitados,
en el noveno mes de 1697 zarpé de Bristol junto con mi compañera Mary Rogers.
Los peligros que tuvimos en el mar,
la fe y el valor que el Señor le dio a mi alma y las cosas
notables que experimenté antes de regresar de América,
sería demasiado grande para relatarlo en esta carta.
Pero puedo decir lo siguiente: Tuve tal evidencia de estar en el lugar adecuado,
que todos los temores fueron quitados.
¡Oh, cuán bueno es confiar en el Señor y ser obediente a Él,
pues Sus misericordias duran para siempre!
Grande es la misericordia y bondad de Dios hacia la pobre humanidad,
y puedo decir para Su alabanza,
que Él ha estado conmigo a través de muchas estrecheces
y dificultades (más de las que puedo enumerar),
y todas estas han obrado para el bien de mi alma.
Sí, tengo buenas razones para creer que cada hijo e hija que Él recibe, Él lo disciplina,
lo trata y lo prueba, y aquellos que no soportan la disciplina de Dios,
resultan ser bastardos y no hijos.
Sin embargo, puedo en verdad decir, como lo dijo un antiguo:
"`Bueno es para mí haber sido afligido`" (Salmo 119:71),
y es bueno seguir la guía del Espíritu de Dios, como Abraham lo hizo fielmente,
quien fue llamado amigo de Dios y no retuvo a su único hijo cuando el
Señor se lo pidió. Es mi creencia que el Señor trata a sus escogidos,
así como es tratado el oro, y que los quiere refinar, así como es refinado el oro.
¿Y qué si Él continúa trayéndonos al horno (de la forma que a Él le plazca),
hasta que seamos siete veces refinados?
Entonces seremos más capaces de llevar la impresión
de Su imagen sobre nosotros en todo lo que hagamos.

El testimonio que Jesús le dio al escriba que deseaba seguirlo es muy cierto:
"`Las zorras tienen guaridas, y las aves del cielo nidos;
mas el Hijo del Hombre no tiene dónde recostar su cabeza.`"
¡Oh, inocente verdad! ¡Oh, Jesús sencillo, manso y humilde! ¿Dónde encuentra Él reposo?
¿Dónde reina Él sin perturbación? Estimado amigo, perdona mi libertad contigo,
pues el amor de Dios me constriñe,
y creo que el Señor te mostrará aún más qué testimonio debes
dar por Su nombre y qué debes sufrir por causa de Él,
si eres fiel.
Porque los tiempos de prueba vendrán, ofensas serán dadas y tomadas,
pero a los que aman al Señor Jesús por encima de todo nada los ofende.
Muchos murmuraron y se ofendieron con Jesús cuando les dijo la verdad,
y muchos de Sus discípulos dejaron de seguirlo.
Entonces les dijo a los doce: "`¿Queréis acaso iros también vosotros?`"
Pero Pedro dijo: "`Señor, ¿a quién iremos?
Tú tienes palabras de vida eterna.
Y nosotros hemos creído y conocemos que tú eres el Cristo, el Hijo del Dios viviente.`"
Así vemos que Dios siempre les ha dado a los fieles creer.
Ya ha venido el Espíritu de Verdad y lleva a Sus seguidores a toda verdad.
Jesucristo, quien es uno con Su Espíritu,
fue ofrecido una vez para llevar los pecados de muchos, y sin ninguna duda,
ha aparecido de nuevo la segunda vez sin relación
con el pecado para salvar a los que le esperan.

¡Oh,
ciertamente la bondad de Dios ha sido muy grande
para con los hijos de los hombres de edad en edad,
y de una generación a otra desde la caída de nuestros primeros padres!
Cuanto más penetra mi mente en esto,
más embargada soy de admiración por Su misericordia y bondad a través de todas Sus dispensaciones,
pero por encima de todo,
por la manifestación de Jesucristo nuestro Patrón santo y Líder celestial.
¡Oh, alma mía, alábalo por el conocimiento de Sus santas huellas,
Al que Dios ha dado como luz para nosotros los gentiles,
y por Su salvación hasta los confines de la tierra! ¡Sí,
Él ha dado Su Espíritu para que more en nosotros
y ha aceptado que nuestras almas moren en Él! ¡Oh,
admirable bondad! ¿Acaso Lo dejaremos?
Él es la Palabra de vida eterna, ¿adónde más podemos ir?
En la medida que algunos sean seguidores de Jesús,
así de lejos quiero seguirlos y ser una con ellos,
y no más allá. Y si alguno se vuelve de Él,
y regresa al mar del que sale la bestia y recibe su marca,
nuestro Líder no debe ser culpado.
Porque Él prosigue Su camino y hace tocar Su trompeta en Sión,
y que una alarma sea sonada en Su monte santo.
Todo aquel que oiga el sonido de la trompeta y no atienda la advertencia,
su sangre caerá sobre su propia cabeza.
Pero el que atienda la advertencia liberará su propia alma.
¡Oh grande es el deber del vigilante! ¡Grande es la benevolencia de Dios!
Tal como es expresada en Ezequiel 33.

Oh, mi estimado amigo, mi corazón está lleno de la bondad del Señor,
pero debo dejar de escribir, no sea que me vuelva demasiado tediosa.
En realidad,
se podría considerar una tontería que yo escriba
de esta manera a alguien de tu posición. Sin embargo,
me encuentro obligada y debo encomendarla a tu juicio, sea el que sea.
Te aseguro que mi corazón es sencillo, hablo con franqueza y sinceridad;
encuentro más seguro hacerlo así y mantenerme en humilde obediencia
al Señor en cualquier cosa que Él requiera de mí. Sé que la sabiduría
de Dios parece necedad a los ojos de los sabios de este mundo,
y sabemos que la sabiduría de este mundo es insensatez para Dios,
y que resultará ser así al final, para esas pobres almas que la estiman grandemente.
Pero las almas de los justos están en la mano del Señor,
y aunque tanto su vida como su muerte sean tomadas
como miseria ante los ojos de los insensatos,
aún así, ningún tormento los tocará y descansarán en paz.

Mi alma te saluda en el amor que es puro,
y permanece siendo tu amiga en verdadera sinceridad,

[.signed-section-signature]
Elizabeth Webb

[.asterism]
'''

__Elizabeth Webb fue una respetada ministra en la Sociedad de Amigos,
en cuyo servicio viajó extensamente por el evangelio.
Como se menciona en la carta anterior,
ella cruzó el Atlántico en 1697 para ministrar entre las colonias americanas,
regresando a Inglaterra en 1699.
Luego su familia emigró de Inglaterra a Pennsylvania en 1700,
donde continuó como ministra hasta su muerte en 1726.
En al menos una ocasión (en 1710),
ella regresó a Inglaterra en obediencia a la guía del Señor. Poco se sabe
sobre este viaje además de su encuentro con Anthony William Boehm en Londres,
a quien es dirigida esta carta.__
